apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      containers:
        - name: booking-service
          image: booking-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: DATABASE_URL
            - name: REDIS_URL
              value: redis://redis:6379/0
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: JWT_SECRET_KEY
            - name: BOOTSTRAP_ADMIN_EMAIL
              value: "admin@example.com"
            - name: BOOTSTRAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-secrets
                  key: BOOTSTRAP_ADMIN_PASSWORD
